# Generated by Django 4.2.4 on 2023-08-02 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(default='5b21ca3eeb7f6fbccd471818', on_delete=django.db.models.deletion.CASCADE, to='core.genre'),
            preserve_default=False,
        ),
    ]
