# Generated by Django 4.2.4 on 2023-08-17 08:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
