# Generated by Django 4.2.4 on 2023-08-22 18:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_movie__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
